### PR TITLE
Fixed Filter not showing issue

### PR DESCRIPTION
**Pull request by AnweshCR7**
https://github.com/predixdesignsystem/px-data-table/issues/178#issue-273550664

### CODE REVIEW

**Comment by evanjd** [comment]
@AnweshCR7 Want some help with the travis issues?

**Comment by AnweshCR7** [comment]
@evanjd 
Any help will be appreciated :)

**Comment by evanjd** [comment]
@AnweshCR7 CI is happy now, do you have someone lined up to review and approve this?

**Comment by AnweshCR7** [comment]
Jamal has Approved the changes... Although I still see the cla-signed failing. How do we rectify that?

**Comment by evanjd** [comment]
@AnweshCR7 Your commits have been made without an e-mail address. cla-bot needs this to verify, without it fails.

You can fix this in future with: https://help.github.com/articles/setting-your-commit-email-address-in-git/

We can still merge without cla-bot's OK, assuming you have signed the CLA.

**Comment by evanjd** [comment]
I've just done a rebase and rewritten your commits with your e-mail to fix cla-bot. Let's let travis finish and we should be good to go.

**Pull request merged**
