### PR TITLE
greedy-height-with-scroll property for px-data-table

### PR DESCRIPTION
**Pull request by tina513**
# Description (greedy-height-with-scroll)
- px-data-table will take full space allocated
- Space will be filled with rows of data
- Any rows that can't fit (based on # of rows shown in dropdown) will vertical scroll

# Enable greedy-height-with-scroll property for px-data-table
- Expose relevant styling class name as styling property for user to modify
- Technically, responds to the greedy-height-with-scroll property in px-data-table

### CODE REVIEW

**Comment by mdwragg** [comment]
Hi,

Thanks for your pull request! Couple of initial comments;

1. There are conflicts that need to be resolved prior to us accepting the PR, can you update your branch with the latest master of the repo.

2. Can you please break out your tests into a separate file? Placing more fixtures on that one page could lead tests to timeout in the (slow) IE VMs used for CI.

Thanks again!

**Comment by randyaskin** [comment]
I spent a little time getting to know this PR today. A few more high level thoughts:

1. The word "greedy" seems a bit confusing and/or  negative. I would recommend changing it everywhere to `scrollOverflow` or `scrollingRows` or something else a bit more clear to the purpose.
2. I find this comment concerning - "For allowing this property work smoothly, container wrapper for px-data-table needs to have display: flex and flex: 1 define." One of the beauties of web components is the encapsulation they provide - the px-data-table shouldn't *care* this specifically about its parent container. Could we find a way to add/remove these on the main `<div>` component within px-data-table.html instead? I feel like the only property of the data-table's parent component that we should care about for this feature is if a specific height is constrained or not.

**Comment by randyaskin** [comment]
Hi Tina - unfortunately this doesn't seem to work cross-browser. The table doesn't show up at all in IE11 anymore, and the scrolling rows functionality doesn't work as expected in Edge either. Do you have access to Sauce Labs or a Windows device to do some troubleshooting? I know Microsoft has some known issues with their support of flexbox, but our usual workarounds didn't help. 🙁

**Comment by jimdefrisco** [comment]
Closing based on comments, conflicts and age

**Pull request closed without merging**
